### ISSUE TITLE
membuat background

### ISSUE THREAD

**Issue by arumkw** [gunadarma-academy/asde-reborn#15]

**Comment by ikaprtys** [comment]
@arumkw rum gambar slider nambah lagi ya

**Comment by ikaprtys** [comment]
bikinin background yang ketinggian air juga

**Comment by arumkw** [comment]
@ikaprtys oke gambar slider nya baru dapet nih dari mereka.. gw masukin yah.. Backgroundnya ntr malem yaaaa :dancer: hahaha
