### ISSUE TITLE
Membuat Burndown Chart

### ISSUE THREAD

**Issue by farfarida** [gunadarma-academy/asde-reborn#17]

**Comment by farfarida** [comment]
ni coba pilih..
http://online.gerrardconsulting.com/iseb/otherdocs/ieee829mtp.pdf 
atau
http://www.tmap.net/sites/default/files/Template_Master_Test_Plan_TMap_NEXT_v2_1%20(1).doc

**Comment by freddyarviando** [comment]
aku pilih yang http://www.tmap.net/sites/default/files/Template_Master_Test_Plan_TMap_NEXT_v2_1%20(1).doc :)

**Comment by ikaprtys** [comment]
iyaa yg bawah aja puk @farfarida
