### ISSUE TITLE
Membuat Event

### ISSUE THREAD

**Issue by farfarida** [gunadarma-academy/asde-reborn#20]

**Comment by ikaprtys** [comment]
freeeed bikin button di slider bisa ga/ bisa kan/ @freddyarviando

**Comment by farfarida** [comment]
@freddyarviando fred.. mw bkin event. nah gue mikirnya event ditaroh di home, yg bagian header itu.. nanti ada tombol jg, ko diklik masuk ke page baru ajaa gpp

**Comment by freddyarviando** [comment]
@ikaprtys harusnya sih bisa kaa..

@farfarida jd eventnya di luar slider yaa?

**Comment by freddyarviando** [comment]
@ikaprtys aku udah bisa bikin button di slider nih kaa :3

**Comment by farfarida** [comment]
@freddyarviando di dlm slider kok hahahha

**Comment by freddyarviando** [comment]
@farfarida oke, udah bisa kok far..
