### ISSUE TITLE
Melakukan User Acceptance Testing

### ISSUE THREAD

**Issue by arumkw** [gunadarma-academy/asde-reborn#32]

**Comment by arumkw** [comment]
Formnya sudah dibuat di http://bit.ly/kuesionerp2c monggo di cek.. @farfarida @ikaprtys @freddyarviando

**Comment by ikaprtys** [comment]
@arumkw rum yg pertanyaan terakhir kelebihan kata2 "lebih" hehehe

**Comment by arumkw** [comment]
@ikaprtys hoo oke" aku benerin..

**Comment by arumkw** [comment]
Untuk user nya http://bit.ly/kuseionerp2cuser
