### ISSUE TITLE
Mengumpulkan gambar

### ISSUE THREAD

**Issue by farfarida** [gunadarma-academy/asde-reborn#7]

**Comment by ikaprtys** [comment]
rum nambah image buat informasi section yoo

**Comment by farfarida** [comment]
gambar buat informasi bagusnya icon i  atau gambar yg brhubungan sm sungai?

**Comment by ikaprtys** [comment]
@farfarida i aja puuuk

**Comment by ikaprtys** [comment]
@freddyarviando fotoooo fred buat diteam section

**Comment by freddyarviando** [comment]
@ikaprtys aku kirim lewat wa yaa

**Comment by arumkw** [comment]
@ikaprtys ukurannya brp ka?

**Comment by ikaprtys** [comment]
@arumkw ukurannya 1280x933
