### ISSUE TITLE
Pembuatan mockup

### ISSUE THREAD

**Issue by farfarida** [gunadarma-academy/asde-reborn#8]

**Comment by arumkw** [comment]
![mockup3](https://cloud.githubusercontent.com/assets/4653565/14130539/d0193afa-f65d-11e5-9970-587396787923.png)
![mockup1](https://cloud.githubusercontent.com/assets/4653565/14130540/d024f48a-f65d-11e5-8998-c61580b73708.png)
![mockup2](https://cloud.githubusercontent.com/assets/4653565/14130541/d0287632-f65d-11e5-9113-18661303f19b.png)

**Comment by farfarida** [comment]
ini yg versi 1 ya? @arumkw

**Comment by ikaprtys** [comment]
iya puk @farfarida ini yg sebelum persetujuan pengembangan. yg versi 2 belum diupload
